### ISSUE TITLE
Feature: User can search for entries

### ISSUE THREAD

**Issue by Jktanisaka** [Jktanisaka/final-project#1]
## ⚙️ Feature

> ##### User can search for other entries

## 📐 Functionality

> #####  Users will be able to type any word into the search bar, submit a search, and receive a list of results.

## 🖼️ Wireframes

> #####

![image](https://user-images.githubusercontent.com/96153171/171037011-97007366-a30d-41cb-87f2-9144f2ac10dc.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle client search requests
- [x] create new route to handle search requests
    - [x] get tagId where label = search input
    - [x] pull all entryId's with the same tagId
    - [x] retrieve list of entries with those entryId's and send to client
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to render the search bar
    - [x] create hash route for search bar and results
    - [x] after search has been submitted, change hash route
    - [x] read new hash route and send fetch request to server
    - [x] render list of entries in response
- [x] Create a component to render results once search triggers

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] Ensure that only items being searched are rendered
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
