### ISSUE TITLE
Feature: User can view entry from a list

### ISSUE THREAD

**Issue by Jktanisaka** [Jktanisaka/final-project#2]
## ⚙️ Feature

> ##### User will be able to view the entry in detail

## 📐 Functionality

> ##### User can click on a result and be taken to the detail view page for that entry

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/96153171/171038863-f5ab592c-0741-4b42-bb0c-7f981a1cb4f6.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle a request for a specific entryId
- [x] retrieve all data for that specific entry to send to the client
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] create a route for the new entry (localhost:3000/#entry?entryId=1)
- [x] Create a component to render the page for the entry
    - [x] component must fetch data from server
    - [x] component will render necessary information (make sure to leave space for file download)
    - [x] component will display image 
- [x] Update entryList component to add hrefs for each entry pulled

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
