### ISSUE TITLE
Feature: User can download files from searched entries

### ISSUE THREAD

**Issue by Jktanisaka** [Jktanisaka/final-project#3]
## ⚙️ Feature

> ##### User can download files from searched entries

## 📐 Functionality

> ##### User will be able to click on a file in the file section of the entry to download that file

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/96153171/172450285-4db8178f-cb99-4640-8c64-9cde0eab3d14.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server
- [x] update route with an additional query to the database for downloadable files
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client
- [x] Update entry view component to render the downloadable files in a new accordion button.
     - [x] file name should be displayed 
     - [x] when clicked on, that particular file will be downloaded

### 🧑‍⚕️ Clean Up
- [x] make sure that only the selected files are being downloaded
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
