### ISSUE TITLE
Feature: User can view entries of another user

### ISSUE THREAD

**Issue by Jktanisaka** [Jktanisaka/final-project#5]
## ⚙️ Feature

> ##### User can view entries of another user

## 📐 Functionality

> ##### User will be able to change the url to view another user's entries

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/96153171/171963140-0809e5c5-f998-408e-9f1b-469f6e67ba37.png)
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle a get request to retrieve all entries for that user
    - [x] create app.get to send a SQL query to return all entries for a specific user (GET /api/users/:userId/entries)
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] on hash change, update the page to render entries for that user (#entries?userId=1)
- [x] Create a component to render the list of all entries of  that user
- [x] list will need to display the title and image of each entry

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
