### ISSUE TITLE
Feature: User can create an account

### ISSUE THREAD

**Issue by Jktanisaka** [Jktanisaka/final-project#7]
## ⚙️ Feature

> ##### User can create an account

## 📐 Functionality

> ##### User will be able to select "sign up" from the navbar and be taken to a sign up screen. User can submit username and password to create an account.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/96153171/171039579-b3ca58cd-f9d3-4258-b669-c4225c3dfb7c.png)
![image](https://user-images.githubusercontent.com/96153171/171039613-0afa3e32-461a-408c-9c5c-ed28e9d2cdf5.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js`  create new route for sign up
     - [x] use argon2 to hash the password
     - [x] store the hashed password in the db 
     - [x] respond to client with 201
- [x] make sure errormiddleware is installed
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] update navbar component to include drop-down menu for navigation
- [x] Create a component to display sign-up page
- [x] upon signup send info to server

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
