### ISSUE TITLE
Feature: User can login

### ISSUE THREAD

**Issue by Jktanisaka** [Jktanisaka/final-project#8]
## ⚙️ Feature

> ##### User can log in

## 📐 Functionality

> ##### user will be able to select "log in" from the navbar and be taken to the log in screen. User can submit credentials and once verified will be logged in.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/96153171/172921646-44a18c74-f55a-452d-a33f-fc15d00057fb.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to create a route for the sign-in request from the client
     - [x] retrieve username and password from the request body
     - [x] make a sql query to retrieve the userID and hashedpassword for the username
     - [x] verify the hashedpassword against the request password
     - [x] if the password verifies, then create a token and send that back to the client along with a payload (userId, username)
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to  display sign-in page
     - [x] On submit, send username and password to the server
     - [x] Once the token  and user object are sent back from the server, put the token into localstorage and set the state of the user object
- [x] Update componentDidMount to retrieve the token from localstorage, if available

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
