### ISSUE TITLE
Feature: User can log out

### ISSUE THREAD

**Issue by Jktanisaka** [Jktanisaka/final-project#9]
## ⚙️ Feature

> ##### User can log out

## 📐 Functionality

> ##### user will be able to select "log out" from the bottom of the navbar and be able to log out.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/96153171/171039794-ad08acf1-f815-40f6-a66b-744fcb822fc7.png)
![image](https://user-images.githubusercontent.com/96153171/171039821-6182ab02-577a-4b46-8cd1-b98bf52d1f14.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client
- [x] update navbar to display logout button at the bottom (button will appear only after user has logged in )
- [x] create handleSignOut function
     - [x] function must remove token in storage and set user state to null
     - [x] page should re-render and navbar should update with appropriate buttons (search, login, sign-up)

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] Verify that user is null and there is no token in the application tab 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
